Fixed report generation
GravenDev/AsyncSupport pull request #2
Opened 2023-08-26 11:28 UTC by g-clems

Fixed report generation
Refactored some code
Fixed Dockerfile entrypoint
Fixed loads of IDE warns
Fixed typo "attachement"
Increased report generation version

2023-08-26 20:03 UTC, enimaloc requested changes

2023-08-26 20:03 UTC, enimaloc commented on README.md
> +| Description         | GravenSupport is the bot used to manage tickets on the Graven - Développement discord server. It can manage tickets and generate reports of those tickets readable by the [tick
Maybe change ticket viewer url ?

2023-08-26 20:03 UTC, enimaloc commented on src/main/java/yt/graven/gravensupport/EventReceiver.java
> +            Ticket ticket = ticketManager.get(event.getAuthor()).orElseThrow();
Thrown an ticket exception ?

2023-08-26 20:03 UTC, enimaloc commented on src/main/java/yt/graven/gravensupport/commands/ticket/create/ModTicketCommand.java
> +            embeds.ticketAlreadyExistsMessage(ticketManager.get(user).orElseThrow().getTo(), false)
Thrown an ticket exception ?

2023-08-26 23:53 UTC, adraug requested changes

2023-08-26 23:53 UTC, adraug commented on src/main/java/yt/graven/gravensupport/commands/ticket/create/ModTicketCommand.java
> +        event.reply("Cette commande n'est pas encore implémentée.")
Ce cas peut-il arriver ?

2023-08-26 23:54 UTC, g-clems commented on src/main/java/yt/graven/gravensupport/commands/ticket/create/ModTicketCommand.java
> +        event.reply("Cette commande n'est pas encore implémentée.")
non

2023-08-27 01:42 UTC, enimaloc commented on src/main/java/yt/graven/gravensupport/commands/ticket/create/ModTicketCommand.java
> +        event.reply("Cette commande n'est pas encore implémentée.")
Dans ce cas on peut enlever cette partie ?

2023-08-27 04:31 UTC, enimaloc approved these changes

2023-08-27 04:35 UTC, g-clems commented on src/main/java/yt/graven/gravensupport/commands/ticket/create/ModTicketCommand.java
> +        event.reply("Cette commande n'est pas encore implémentée.")
Enfait si on l'attein

2023-09-04 16:47 UTC, g-clems commented
Bon on va dire que c'est bon je merge

2023-09-04 16:47 UTC, merged